// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_refresh_token.sql

package database

import (
	"context"
)

const updateRefresh = `-- name: UpdateRefresh :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE token = $1
`

func (q *Queries) UpdateRefresh(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, updateRefresh, token)
	return err
}
